### ISSUE TITLE
Decouple external library calls from source code.

### ISSUE THREAD

**Issue by ParadoxZero** [ParadoxZero/libgeneric#22]
External library calls including `malloc` and `callac` etc. to be removed and replaced by a macro.

The macro can be defined when the library will be used.

This will enable the library to be used in different contexts including freestanding environment.

**Comment by TravorLZH** [comment]
It seems like you are going to use it in your Operating System. It is the system developer’s responsibility to implement malloc and/or free, or everything is fixed size. You can either port **liballoc** to your OS or implement a **internal memory allocator** in your library instead of removing dynamic stuff. It will be easier to make it an offer to OS instead of to this library.

**Comment by TravorLZH** [comment]
Could you explain more about replacing malloc/free with macros

**Comment by ParadoxZero** [comment]
Replace `malloc` with something like `gMalloc`.

The programmer will define the `gMalloc` macro when porting the library for their system.

e.g. 

```c
#define gMalloc malloc
```

**Comment by TravorLZH** [comment]
I think this is reluctant because it won’t be convenient for users and porting. There is really no need of that macro. And are you porting this to your OS?

**Comment by ParadoxZero** [comment]
Something to be done by the platform the library is to be deployed, not the user.

**Comment by ParadoxZero** [comment]
Moved the backlog to project
